a = 1000
b = 1200
c = 800
amount = a+b+c
purchased_amount = 2000
balance = amount - purchased_amount
a1 = balance/3
print("Balance amount =",balance)
print("Returning amount for each person =",a1)
