x = float(input("Enter the first number :"))
y = float(input("Enter the second number :"))
z = float(input("Enter the third number :"))
max = max(x,y,z)
min = min(x,y,z)
print("Maximum number =",max)
print("Minimum number =",min)